### ISSUE TITLE
Error: source file could not be loaded`

### ISSUE THREAD

**Issue by budingts** [domnulnopcea/docker-libreoffice-headless#1]
the host has  /tmp/aa.pptx

when i run 

`docker run -v /tmp/:/tmp domnulnopcea/libreoffice-headless libreoffice --headless --convert-to pdf aa.pptx --outdir /tmp`

show the error

`W: Unknown node under /registry/extlang: deprecated
W: Unknown node under /registry/grandfathered: comments
W: Unknown node under /registry/grandfathered: comments
W: Unknown node under /registry/extlang: deprecated
W: Unknown node under /registry/grandfathered: comments
W: Unknown node under /registry/grandfathered: comments
Error: source file could not be loaded`

**Comment by domnulnopcea** [comment]
do not mount the external /tmp inside /tmp

/tmp is a "special" folder in linux. this docker is based on a linux distribution

mount for example inside /xyz

**Comment by domnulnopcea** [comment]
@budingts does this fix your issue?
