### ISSUE TITLE
Not working inside child directories

### ISSUE THREAD

**Issue by georgejdanforth** [domnulnopcea/docker-libreoffice-headless#2]
Hi, when I try to use this inside child directories of my home directory, e.g.
```
sudo docker run -v /Users/georgejdanforth/my-project-dir/docs:/tmp domnulnopcea/libreoffice-headless libreoffice --headless --convert-to pdf tmp/my-file.docx --outdir /tmp
```
I get no terminal output, my file is not converted, and an empty subdirectory called `hsperfdata_root` is created.  However, when I just run it on a file in my home directory, e.g.
```
sudo docker run -v /Users/georgejdanforth:/tmp domnulnopcea/libreoffice-headless libreoffice --headless --convert-to pdf tmp/my-file.docx --outdir /tmp
```
everything works as expected.

I was hoping you might be able to shed some light on what might be going on here.  Thank you!

**Comment by domnulnopcea** [comment]
hi @georgejdanforth please check this issue #1

**Comment by georgejdanforth** [comment]
Hi @domnulnopcea, thanks for your response.  Please correct me if I'm wrong but I don't believe this is the same problem.  I am not trying to use my system's `/tmp` directory, and when I run it like this I'm not getting an `Error: source file could not be loaded`

**Comment by domnulnopcea** [comment]
you are mounting inside /tmp

use any other folder like /xyz and it will work. pls confirm

**Comment by georgejdanforth** [comment]
this appears to just be a Mac issue, works fine on ubuntu :\
